# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura/CMakeFiles /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named photo_manufactura

# Build rule for target.
photo_manufactura: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 photo_manufactura
.PHONY : photo_manufactura

# fast build rule for target.
photo_manufactura/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/build
.PHONY : photo_manufactura/fast

#=============================================================================
# Target rules for targets named photo_manufactura_autogen_timestamp_deps

# Build rule for target.
photo_manufactura_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 photo_manufactura_autogen_timestamp_deps
.PHONY : photo_manufactura_autogen_timestamp_deps

# fast build rule for target.
photo_manufactura_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura_autogen_timestamp_deps.dir/build.make CMakeFiles/photo_manufactura_autogen_timestamp_deps.dir/build
.PHONY : photo_manufactura_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named photo_manufactura_autogen

# Build rule for target.
photo_manufactura_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 photo_manufactura_autogen
.PHONY : photo_manufactura_autogen

# fast build rule for target.
photo_manufactura_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura_autogen.dir/build.make CMakeFiles/photo_manufactura_autogen.dir/build
.PHONY : photo_manufactura_autogen/fast

#=============================================================================
# Target rules for targets named image_processing

# Build rule for target.
image_processing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_processing
.PHONY : image_processing

# fast build rule for target.
image_processing/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/CMakeFiles/image_processing.dir/build.make src/image_processing/CMakeFiles/image_processing.dir/build
.PHONY : image_processing/fast

#=============================================================================
# Target rules for targets named generate_photo_adjustment

# Build rule for target.
generate_photo_adjustment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_photo_adjustment
.PHONY : generate_photo_adjustment

# fast build rule for target.
generate_photo_adjustment/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/CMakeFiles/generate_photo_adjustment.dir/build.make src/image_processing/CMakeFiles/generate_photo_adjustment.dir/build
.PHONY : generate_photo_adjustment/fast

#=============================================================================
# Target rules for targets named trigger_photo_adjustment_gen

# Build rule for target.
trigger_photo_adjustment_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 trigger_photo_adjustment_gen
.PHONY : trigger_photo_adjustment_gen

# fast build rule for target.
trigger_photo_adjustment_gen/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/CMakeFiles/trigger_photo_adjustment_gen.dir/build.make src/image_processing/CMakeFiles/trigger_photo_adjustment_gen.dir/build
.PHONY : trigger_photo_adjustment_gen/fast

#=============================================================================
# Target rules for targets named image_processing_test

# Build rule for target.
image_processing_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_processing_test
.PHONY : image_processing_test

# fast build rule for target.
image_processing_test/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/CMakeFiles/image_processing_test.dir/build.make src/image_processing/CMakeFiles/image_processing_test.dir/build
.PHONY : image_processing_test/fast

#=============================================================================
# Target rules for targets named raw_processing

# Build rule for target.
raw_processing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raw_processing
.PHONY : raw_processing

# fast build rule for target.
raw_processing/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/raw_processing_build/CMakeFiles/raw_processing.dir/build.make src/image_processing/raw_processing_build/CMakeFiles/raw_processing.dir/build
.PHONY : raw_processing/fast

#=============================================================================
# Target rules for targets named raw_processing_test

# Build rule for target.
raw_processing_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raw_processing_test
.PHONY : raw_processing_test

# fast build rule for target.
raw_processing_test/fast:
	$(MAKE) $(MAKESILENT) -f src/image_processing/raw_processing_build/CMakeFiles/raw_processing_test.dir/build.make src/image_processing/raw_processing_build/CMakeFiles/raw_processing_test.dir/build
.PHONY : raw_processing_test/fast

#=============================================================================
# Target rules for targets named tasks

# Build rule for target.
tasks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks
.PHONY : tasks

# fast build rule for target.
tasks/fast:
	$(MAKE) $(MAKESILENT) -f src/tasks/CMakeFiles/tasks.dir/build.make src/tasks/CMakeFiles/tasks.dir/build
.PHONY : tasks/fast

#=============================================================================
# Target rules for targets named tasks_autogen_timestamp_deps

# Build rule for target.
tasks_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks_autogen_timestamp_deps
.PHONY : tasks_autogen_timestamp_deps

# fast build rule for target.
tasks_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/tasks/CMakeFiles/tasks_autogen_timestamp_deps.dir/build.make src/tasks/CMakeFiles/tasks_autogen_timestamp_deps.dir/build
.PHONY : tasks_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named tasks_autogen

# Build rule for target.
tasks_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tasks_autogen
.PHONY : tasks_autogen

# fast build rule for target.
tasks_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/tasks/CMakeFiles/tasks_autogen.dir/build.make src/tasks/CMakeFiles/tasks_autogen.dir/build
.PHONY : tasks_autogen/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) $(MAKESILENT) -f src/model/CMakeFiles/model.dir/build.make src/model/CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named model_autogen_timestamp_deps

# Build rule for target.
model_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model_autogen_timestamp_deps
.PHONY : model_autogen_timestamp_deps

# fast build rule for target.
model_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/model/CMakeFiles/model_autogen_timestamp_deps.dir/build.make src/model/CMakeFiles/model_autogen_timestamp_deps.dir/build
.PHONY : model_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named model_autogen

# Build rule for target.
model_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 model_autogen
.PHONY : model_autogen

# fast build rule for target.
model_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/model/CMakeFiles/model_autogen.dir/build.make src/model/CMakeFiles/model_autogen.dir/build
.PHONY : model_autogen/fast

#=============================================================================
# Target rules for targets named controller

# Build rule for target.
controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controller
.PHONY : controller

# fast build rule for target.
controller/fast:
	$(MAKE) $(MAKESILENT) -f src/controller/CMakeFiles/controller.dir/build.make src/controller/CMakeFiles/controller.dir/build
.PHONY : controller/fast

#=============================================================================
# Target rules for targets named controller_autogen_timestamp_deps

# Build rule for target.
controller_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controller_autogen_timestamp_deps
.PHONY : controller_autogen_timestamp_deps

# fast build rule for target.
controller_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/controller/CMakeFiles/controller_autogen_timestamp_deps.dir/build.make src/controller/CMakeFiles/controller_autogen_timestamp_deps.dir/build
.PHONY : controller_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named controller_autogen

# Build rule for target.
controller_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 controller_autogen
.PHONY : controller_autogen

# fast build rule for target.
controller_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/controller/CMakeFiles/controller_autogen.dir/build.make src/controller/CMakeFiles/controller_autogen.dir/build
.PHONY : controller_autogen/fast

#=============================================================================
# Target rules for targets named ui

# Build rule for target.
ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui
.PHONY : ui

# fast build rule for target.
ui/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui.dir/build.make src/ui/CMakeFiles/ui.dir/build
.PHONY : ui/fast

#=============================================================================
# Target rules for targets named ui_autogen_timestamp_deps

# Build rule for target.
ui_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_autogen_timestamp_deps
.PHONY : ui_autogen_timestamp_deps

# fast build rule for target.
ui_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui_autogen_timestamp_deps.dir/build.make src/ui/CMakeFiles/ui_autogen_timestamp_deps.dir/build
.PHONY : ui_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ui_autogen

# Build rule for target.
ui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ui_autogen
.PHONY : ui_autogen

# fast build rule for target.
ui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/ui/CMakeFiles/ui_autogen.dir/build.make src/ui/CMakeFiles/ui_autogen.dir/build
.PHONY : ui_autogen/fast

photo_manufactura_autogen/mocs_compilation.o: photo_manufactura_autogen/mocs_compilation.cpp.o
.PHONY : photo_manufactura_autogen/mocs_compilation.o

# target to build an object file
photo_manufactura_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/photo_manufactura_autogen/mocs_compilation.cpp.o
.PHONY : photo_manufactura_autogen/mocs_compilation.cpp.o

photo_manufactura_autogen/mocs_compilation.i: photo_manufactura_autogen/mocs_compilation.cpp.i
.PHONY : photo_manufactura_autogen/mocs_compilation.i

# target to preprocess a source file
photo_manufactura_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/photo_manufactura_autogen/mocs_compilation.cpp.i
.PHONY : photo_manufactura_autogen/mocs_compilation.cpp.i

photo_manufactura_autogen/mocs_compilation.s: photo_manufactura_autogen/mocs_compilation.cpp.s
.PHONY : photo_manufactura_autogen/mocs_compilation.s

# target to generate assembly for a file
photo_manufactura_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/photo_manufactura_autogen/mocs_compilation.cpp.s
.PHONY : photo_manufactura_autogen/mocs_compilation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/photo_manufactura.dir/build.make CMakeFiles/photo_manufactura.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... controller_autogen"
	@echo "... controller_autogen_timestamp_deps"
	@echo "... model_autogen"
	@echo "... model_autogen_timestamp_deps"
	@echo "... photo_manufactura_autogen"
	@echo "... photo_manufactura_autogen_timestamp_deps"
	@echo "... tasks_autogen"
	@echo "... tasks_autogen_timestamp_deps"
	@echo "... trigger_photo_adjustment_gen"
	@echo "... ui_autogen"
	@echo "... ui_autogen_timestamp_deps"
	@echo "... controller"
	@echo "... generate_photo_adjustment"
	@echo "... image_processing"
	@echo "... image_processing_test"
	@echo "... model"
	@echo "... photo_manufactura"
	@echo "... raw_processing"
	@echo "... raw_processing_test"
	@echo "... tasks"
	@echo "... ui"
	@echo "... photo_manufactura_autogen/mocs_compilation.o"
	@echo "... photo_manufactura_autogen/mocs_compilation.i"
	@echo "... photo_manufactura_autogen/mocs_compilation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/duongtran/sciebo/SCIEBO_CLOUD/G_REST/S11_EDA/photo-manufactura/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

